### PR TITLE
Add support for pagination, resolves issue #4

### PR DESCRIPTION
**Pull request by azillion**
Untested and probably needs more work.

### CODE REVIEW

**Comment by azillion** [comment]
Resolves issue #4

**Comment by halcy** [comment]
Hm. I'm having trouble testing this. My python somehow seems to choke on the type hinting, which is a bit weird. I've thought about it for a while, though, so here's a writeup.

As far as I can tell, it's a good start, but not quite right yet. Best would be if the fetch was super transparent to users. Ideally, what I think should happen is:

1) if there is no link header, the parsed json is returned as is. This seems easy to do.
2) if there IS a link header, a response object is returned. it iterates not over responses, but over the _list_ that is the top-level of the response object and, when it reaches the end of the list, fetches more data.
3) fetch_all et cetera can remain as is, of course, as can the function to get the actual response (there should probably also be an explicit method to get the next page response object)

To not break expectations and probably existing code, the interface should probably also be list-like rather than iterator-like (i.e. allow random access), which would require bidirectional iteration (it's probably fine not to cache anything, though, and just document that certain access patterns are a bad idea).

With all that, I think it also makes sense for the response object to be in its own file, as the streaming code is.

Anybody see any glaring issues with this?

**Comment by halcy** [comment]
Also, as a brief development guideline: Mastodon.py should work with python2 as well as python3, so type annotations, @property, &c are probably out. I should likely set up some tests and CI or whatever.

**Comment by azillion** [comment]
Sounds great, hopefully I'll have time here soon to revise the PR to fit your ideas. And no problem, I can take out all the specific python3 stuff.

**Comment by halcy** [comment]
My mind has, in the meanwhile, been changed about this - there's probably too many pitfalls where a user might accidentally cause a lot of requests due to de-lazyfying something. Explicit pagination is probably actually better.

**Pull request closed without merging**
