### PR TITLE
more robust handling of pagination Link headers

### PR DESCRIPTION
**Pull request by codl**
during a cursory investigation for #163 I found that the code handling
Link headers would not handle non-numeric post IDs like pleroma's
flakeIDs correctly

IDs starting with a number would be truncated to the first non-digit,
and IDs not starting with a number would throw. Thankfully, all flakeIDs
generated so far start with 9. Maybe 8 for the earliest ones, I'm not
sure. Either way, so far it would only have misbehaved when using the
pagination functions or accessing the _pagination_prev and
_pagination_next attributes directly

### CODE REVIEW

**Comment by codl** [comment]
sshush codecov i will make tests but not now because it is 4 AM

**Comment by codl** [comment]
added a test, for this and for _pagination_prev and _pagination_next in general. i added requests-mock as a dependency and mocked the whole thing because i didn't want to make an elaborate setup script for a pleroma instance just to record one cassette

**Comment by codl** [comment]
i added a test, for this and for `_pagination_next` and `_pagination_prev` attributes in general

i added requests-mock as a dependency and mocked the whole exchange because i didn't want to make an elaborate pleroma set up script just to record one cassette

**Comment by halcy** [comment]
sounds good!

**Pull request merged**
