### PR TITLE
Add support for sensitive toots and visibility settings.

### PR DESCRIPTION
**Pull request by fpiesche**
As the API now supports these, I've added options to toot privately or with media marked as sensitive.

### CODE REVIEW

**Comment by halcy** [comment]
Great! Thank you very much!

There are some things that I think need to be adressed before merge. One is documentation - the new parameters should be documented. Another is default visibility - can we respect the profiles setting here? For the interface, do we expect to need more than "public" or "private", and if we do not, should we just use a boolean "private" parameter? 

A smaller thing that I think should be changed before this is merged is the toot()-function. It is supposed to be a test only wrapper and should only ever have one parameter.

**Comment by fpiesche** [comment]
Making the default visibility depend on the profile setting seems like a good plan; I’ll look into that and document the parameters better.

I don’t think a boolean would be enough here, since toot privacy is more granular than account privacy (between private, public and unlisted), and I’d rather not break it up into two separate parameters as that would change the behaviour vs the actual API.

I was unaware that toot() was meant to be a test-only thing so I’ll ditch the parameter from that.

**Comment by halcy** [comment]
If it is more granular, then that makes sense - I didn't realize "unlisted" was part of the same block of options (though, yes, that makes sense). In that case, a (documented) string parameter is the best, I think, but it should probably be checked for validity (I think other enum-y parameters, like in the timeline getter, are also checked)

**Comment by fpiesche** [comment]
I've implemented those changes now, but there's one thing left - as it is, every status_post() would check the account's privacy status. I *think* this is the best approach in case the privacy status gets changed within a single Mastodon.py session, but it *does* double the amount of API requests made. Is that at all acceptable, or should we just check the account privacy status once on login and then ignore any changes during the session?

**Comment by Gargron** [comment]
If you're unsure feel free not to pass that parameter, the server will then default to private for locked accounts and public otherwise.

**Comment by fpiesche** [comment]
Oh, excellent! Would that also happen if the parameter is empty, or would it just not want to be present at all? The former would be trivial to implement in Python, the latter might need some jiggling of function parameters...

**Comment by Gargron** [comment]
Yeah it can be empty

**Comment by halcy** [comment]
That seems good! Thank you for your work! I merged it, will do a maint release of the pypi package with the changes in it probably next Tuesday (I am gone over the weekend)

**Pull request merged**
