### PR TITLE
Fix gotosocial issues

### LINKED ISSUE #246: Rate limit calculation crashes using GoToSocial
When logging in to a GoToSocial instance Mastodon.py crashes at the rate limit calculation

### PR DESCRIPTION
**Pull request by fwaggle**
I found two issues I had to fix in order to make this library work with gotosocial. I put them as separate commits in case you want to cherry-pick either of them, because you may disagree with how they're solved.

This should fix #246 - I don't have any grief with it after these changes are applied (other than the non-existent/unsupported endpoints not working). I couldn't figure out your tests, not sure if I broke anything, I certainly didn't add any new test cases.

I know you're busy, so just throwing this out there into the void in case it's useful for others.

### CODE REVIEW

**Comment by halcy** [comment]
Thanks, merging this. Will do a fix release tomorrow, and then start working on integrating new features

**Comment by fwaggle** [comment]
@mirabilos Is that using the `Mastodon.log_in()` method? I couldn't get that to work, it might be an additional bug. This worked for me:

```
from mastodon import Mastodon
m = Mastodon.create_app('Python Test', api_base_url='https://your.gts.instance/, to_file = 'app.secret')
m.auth_request_url(scopes=['read'])
```

This should return a URL where you can perform an OAUTH login, after which it'll give you a token. Then you can:

```
m.log_in(code='BIG_OAUTH_CODE_FROM_GTS_LOGIN_HERE', to_file='user.secret', scopes=['read'])
```

Note that `scopes` here *must* match exactly what you specified when you created the token. You should be logged in at this point, and now (and next time, skip the app creation and login steps unless you log yourself out) you can use:

```
m = Mastodon(access_token='user.secret', api_base_url = 'https://your.gts.instance/', version_check_mode='none')

```
m.account_verify_credentials()
m.instance_nodeinfo()
# etc etc
```

Hope that helps!

**Comment by mirabilos** [comment]
… apparently by generating a token from the web with https://takahashim.github.io/mastodon-access-token/ and using that… ☹☹☹

**Comment by mirabilos** [comment]
How do you get this working with GtS? All I get is:

    mastodon.Mastodon.MastodonIllegalArgumentError: Invalid user name, password, or redirect_uris: ('Mastodon API returned error', 400, 'Bad Request', 'invalid_request')

**Comment by mirabilos** [comment]
James Fraser dixit:

***@***.*** Is that using the `Mastodon.log_in()` method? I couldn't get
***@***.*** to work, it might be an additional bug. This worked for me:

>m.auth_request_url(scopes=['read'])

>This should return a URL where you can perform an OAUTH login, after

OIC, this probably was it. The software (feediverse.py) I was trying
to use has:

        client_id, client_secret = Mastodon.create_app(…)
        m = Mastodon(client_id=client_id, client_secret=client_secret, api_base_url=url)

So this OAUTH PoS always requires involving a webbrowser? 🤮

bye,
//mirabilos
-- 
  "Using Lynx is like wearing a really good pair of shades: cuts out
   the glare and harmful UV (ultra-vanity), and you feel so-o-o COOL."
                                         -- Henry Nelson, March 1999

**Pull request merged**
