### PR TITLE
Fix auth_request_url

### PR DESCRIPTION
**Pull request by azillion**
Now able to specify the needed scope for the client.
Defaults to read write follow

### CODE REVIEW

**Comment by halcy** [comment]
I'd prefer to not have 9e06f3e in there. I know how to do that offline, but I have no idea how to do it from the github web interface, so I'll merge tomorrow when I'm at a Real Computer.

**Comment by azillion** [comment]
That was my fault, sorry. I was working on a branch of that and it's not done yet, didn't mean to push that into this pull request

**Comment by halcy** [comment]
Cherry-picked relevant commits instead of merging. If you have a moment, please check if I got everything.

Thank you for your work!

**Comment by azillion** [comment]
You got everything, thanks!

**Pull request closed without merging**
