### PR TITLE
Update Mastodon.py

### PR DESCRIPTION
**Pull request by no-boot-device**

### CODE REVIEW

**Comment by halcy** [comment]
This looks to me like it could cause problems with hosted applications. What is wrong with the del that is in there currently?

**Comment by no-boot-device** [comment]
A monkeypatch of the requests module gets around it.

**Comment by no-boot-device** [comment]
That's a good point though, perhaps just simply changing it to go to `test.invalid` instead or throw an exception that should be handled by hosted programs would be better?

**Comment by halcy** [comment]
Honestly, all of that seems complicated and fragile for something that can (and I’m sure, by now, has been) patched out of _this_ code, either in source or monkeypatched, in 5 minutes flat.

I am against anything that’ll mean random people will have to modify their code or potentially face breakage. Throwing a network error might be good, those would generally have to be caught anyways.

**Comment by no-boot-device** [comment]
I'm gonna remake this pull request since I'm pretty sure if you were to pull it now it'd add all 4 commits

**Pull request closed without merging**
