### PR TITLE
remove six dependecy

### PR DESCRIPTION
**Pull request by a-detiste**
six was once usefull to support python 2 & 3 with the same codebase

https://wiki.debian.org/Python3-six-removal

### CODE REVIEW

**Comment by a-detiste** [comment]
So it's a step in the right direction but I can't wrap my mind around this ... wrapper ... right now.

**Comment by a-detiste** [comment]
Ping

**Comment by halcy** [comment]
hey

sorry, I got distracted last time I was doing maintenance, and then work got a bit much. I will get back to it - eventually. But it might be a month or two. Just wanted to say - this isn't forgotten, but I am going to have to take a bit of time to get to it.

**Comment by halcy** [comment]
Thanks, merged (finally)

**Comment by halcy** [comment]
thanks, merged! finally!

**Pull request merged**
