### PR TITLE
Allow specifying the file name for media uploads

### PR DESCRIPTION
**Pull request by animeavi**
The parameter is optional so this change is backwards compatible

### CODE REVIEW

**Comment by arittner** [comment]
Hi!

I'll check if the definition of a filename will have any effect. I need to check it with mastodon instances. Also, I'm not sure what happening on download or accessing the media via links. If we cannot access the filename anymore, it makes no sense to define it.

**Comment by ioistired** [comment]
It doesn't really have an effect on Mastodon but Pleroma supports custom filenames.

**Comment by arittner** [comment]
> It doesn't really have an effect on Mastodon but Pleroma supports custom filenames.

Ah, thank you for the clarification.

**Comment by halcy** [comment]
Thank you for the contribution, merging this. Reminder for self to write a test tomorrow that covers this.

**Pull request merged**
