### PR TITLE
migrate to pyproject.toml

### PR DESCRIPTION
**Pull request by codl**
#276

Stuff to consider that's potentially out of scope:
- Given that extras cannot be built programatically here and the `[test]` extra used to be programatically built out of the `[webpush]` and `[blurhash]` extras and some more stuff, I have copied the webpush and blurhash deps into `[test]` and left a note to update one when the other is changed, but someone is bound to miss the note and they will fall out of sync. Another option would be removing webpush and blurhash deps from `[test]`, changing the tests README and CI scripts to pull all three extras, and making the related tests skip when the optional deps aren't present. That's potentially a breaking change if someone's got a script installing `[dev]` and assuming it'll get everything. **Should I do that?**
- I kept blurhash as both a regular dependency and part of the `[blurhash]` extra, even though I don't think that's doing what was intended (see https://github.com/halcy/Mastodon.py/issues/276#issuecomment-1520458273). **Should I remove it from the main dependencies?**
- What's left in setup.cfg cannot be migrated over afaik but I'm also not sure that any of it is useful anymore
  - The bdist_wheel section generates universal wheels which work on both python 2 and 3. **Does Mastodon.py still work on python 2?**
  - The build_sphinx section specifies settings for `python setup.py build_sphinx`, which is deprecated by Sphinx and planned to be removed from the next major version. **Does anyone use setup.py build_sphinx?**
  - The aliases section aliases `python setup.py test` to `pytest`. **How likely is it that anyone uses this alias?**

### CODE REVIEW

**Comment by halcy** [comment]
Test deps: Fine, imo - switching to pyproject.toml seems like it would break build automations and peoples workflows anyways if anyone has those for this, so might as well. Same goes for remaining stuff in setup.py - probably not worth keeping

blurhash: the goal would be to allow an install with an extra component that is selected by default but can be deselected. I don’t know what the correct way to achieve this is.

**Comment by codl** [comment]
> Test deps: Fine, imo - switching to pyproject.toml seems like it would break build automations and peoples workflows anyways if anyone has those for this, so might as well. Same goes for remaining stuff in setup.py - probably not worth keeping

Alright, will make those changes. For what it's worth, I think switching to pyproject.toml will only break workflows that are running setuptools from >5 years ago, or very fucked up setups that parse setup.py by hand.
 
> blurhash: the goal would be to allow an install with an extra component that is selected by default but can be deselected. I don’t know what the correct way to achieve this is.

I don't think this is possible, The best option might be to remove blurhash from the default deps and change documentation to recommend that people `pip install Mastodon.py[blurhash]`. But this *will* break workflows.

**Comment by codl** [comment]
Did the needful, this should be good to merge. I'm going to leave figuring out what to do with blurhash for another PR.

**Comment by halcy** [comment]
Thanks, looks good, merging

**Pull request merged**
