### PR TITLE
add timeouts to streams

### LINKED ISSUE #127: should StreamListener keep track of heartbeats and close stream if n of them are missed?
If a client goes offline for a while then comes back online, the StreamListener will keep the stream open even though the server at the other end has already closed the connection. While an application *can* listen for heartbeats and do its own checks, that logic is going to be the same in every application. It's also a bit counter-intuitive.

I propose that, at least by default, StreamListener should close the stream after 5 minutes. Or a configurable length of time. ~~I'm not sure how often heartbeats are sent~~ e: seems to be every 15 seconds

### PR DESCRIPTION
**Pull request by codl**
fixes #127

adds both the connect timeout as set in the constructor, and a read timeout as specified in arguments

~~I haven't taken the time to test this yet 😬~~

### CODE REVIEW

**Comment by codl** [comment]
how the heck did i increase coverage

**Comment by codl** [comment]
ok after a little bit of testing (read: unplugging network cables and plugging them back in) this seems to work great

i'd love to add a unit test for this but i don't know how to test it. I doubt vcr.py supports streaming

**Comment by halcy** [comment]
Do you think we should catch requests.ReadTimeout and re-throw it? We rethrow I think all or nearly all errors presently.

**Comment by halcy** [comment]
Also, is there a reason stream_user is not included, or just an oversight?

**Comment by halcy** [comment]
merged.

**Comment by codl** [comment]
yay!

**Pull request merged**
